spring:
  application:
    name: wallet-service

  datasource:
    url: jdbc:postgresql://localhost:5433/wallet_db
    username: wallet_user
    password: wallet_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: phucbuivan99@gmail.com
    password: kswe rdrr zkvz neoy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: mySecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLongForSecurity
  expiration: 86400000

# App Configuration
app:
  reset-password:
    frontend-url: http://localhost:5173/reset-password

server:
  port: 8080
